### ISSUE TITLE
Wrong code point for MODIFIER LETTER SMALL TURNED ALPHA

### ISSUE THREAD

**Issue by dscorbett** [alif-type/xits#64]
The glyph for U+1D9B MODIFIER LETTER SMALL TURNED ALPHA is uni1D98 instead of uni1D9B.

**Comment by khaledhosny** [comment]
Thanks. You might want to check if https://github.com/stipub/stixfonts are affected as well.

**Comment by dscorbett** [comment]
That doesn’t seem to have fixed it.
```
$ hb-shape -u 1D98 XITS-Regular.otf
[uni1D9B=0+441]
$ ttx -o /dev/stdout -t cmap XITS-Regular.otf 2>/dev/null | grep '<map code="0x1d98"' | uniq
      <map code="0x1d98" name="uni1D9B"/><!-- LATIN SMALL LETTER ESH WITH RETROFLEX HOOK -->
```

**Comment by khaledhosny** [comment]
FontForge was playing tricks on me, there is one more glyph encoding field not visible from GUI (had to “re-encode” the font to fix it).
