### ISSUE TITLE
Multiplication dot is too large

### ISSUE THREAD

**Issue by Polda18** [alif-type/xits#65]
Hi. May I ask question about where do you get the size for the multiplication dot? Because it is far too large, resembling rather a list bullet than a multiplication dot sign. I guess that the whole operator section was somehow shifted. If I use as a default font Cambria Math, and turn it into XITS Math before typing expression, the Word is actually smart enough to remember how big the dot should really be, and makes it in Cambria Math font and rest is typed again by XITS Math. But when I somehow choose XITS Math as a default font for equations and/or change the font to XITS Math from Cambria Math afterwards, it doesn't follow these rules and creates a big blob instead of a nice small dot. I have quite unpleasant teacher who is hungry to seek for any issue with the stylistic format and given that nature I've got some points down because of that...

**Comment by khaledhosny** [comment]
Can you specify exactly what character (Unicode code point) you are referring to? May be also a screenshot.

Almost all glyphs come from [STIX Math](https://github.com/stipub/stixfonts/) font (version 1, but I don’t think many non-alphabetic glyphs changed in version two).

**Comment by Polda18** [comment]
u2219
![image](https://user-images.githubusercontent.com/25118993/54727012-cfbc6d00-4b75-11e9-8b4a-72f4082067fb.png)

**Comment by Polda18** [comment]
Don't mind the Skype :D :D

**Comment by khaledhosny** [comment]
I don’t think U+2219 BULLET OPERATOR is the multiplication dot, that should be U+22C5 DOT OPERATOR.

**Comment by Polda18** [comment]
So MS Word Equation Editor basically uses wrong glyph for multiplication
dot? Funny that Cambria Math's one seems okay.
Naturally, I am using Equation Editor to place mathematical symbols in
equations. If the font is designed to work with MS Word's Equation Editor,
shouldn't it be actually optimised for it? Because it still places symbols
in Cambria Math, not the font I selected, which is XITS Math. I wish that
they never removed the old Equation Editor from Office 2003, that was quite
good editor. Whatever. Thanks for your assistance :)

**Comment by khaledhosny** [comment]
How do you insert the multiplication dot, I couldn’t find a way in my copy of Word other than inserting the Unicode character from the symbols table.

**Comment by Polda18** [comment]
[image: image.png]
This is the way to do it in Word. Navigate to Insert card, then click
Equation. It brings you to this screen. The multiplication dot is the one
highlighted. In XITS Math however, it inserts the bullet instead. Word
replaces the symbols inserted using Equation Editor by Cambria Math
instead. I don't know how Cambria Math solves the mathematical symbols
inclusion, but it is definitely different solution than in XITS Math it
seems. This is how the equation looks like after changing it entirely to
XITS Math:
[image: image.png]
Notice the large bullet instead of small dot. All I did is to select the
entire equation and change the font to XITS Math. If the equation editor is
supposed to insert multiplication dot, then why after changing it to XITS
Math, it's bullet?

**Comment by khaledhosny** [comment]
The images are not shown (GitHub scraps the attachment when you reply via email).

**Comment by Polda18** [comment]
Dammit. I'll copy it and paste it directly in the Github topic.

čt 21. bře 2019 10:20 odesílatel Khaled Hosny <notifications@github.com>
napsal:
