### ISSUE TITLE
Wrong angle bracket sizes under unicode-math + fontspec

### ISSUE THREAD

**Issue by AndrewSwann** [alif-type/xits#66]
I open this issue

https://github.com/wspr/unicode-math/issues/277#issue-42897406

for unicode-math, but it is not clear where the issue really lies, perhaps with amsmath, perhaps with XITS.  Anyway 

```
\documentclass{article}

\usepackage{mathtools,unicode-math}
\unimathsetup{math-style=TeX}
\setmathfont{XITS Math}
%\setmathfont{TeX Gyre Pagella Math}

\begin{document}
  \begin{displaymath}
    \bigl\langle \langle p \rangle \bigr\rangle
    \quad \bigl( ( r ) \bigr)
    \quad \bigl\{ \{ s \} \bigr\}
  \end{displaymath}

\end{document}
```

produces under lualatex

![Screenshot 2019-03-24 at 10 04 37](https://user-images.githubusercontent.com/8794645/54877255-5db98180-4e1c-11e9-9354-833704b98105.png)

with the angle brackets not sizing correctly under `\big`.  Changing away from XITS to another font gives correctly scaled brackets.   RuxiZhang42 https://github.com/wspr/unicode-math/issues/277#issuecomment-475920904 points to this coming from a small height for the ordinary parenthesis in XITS, which amsmath then uses as the basis for deciding the new sizes.  Would it be possible to fix the XITS size so this works without having to patch unicode-math or amsmath?

**Comment by khaledhosny** [comment]
The glyphs are the original STIX glyphs, and it is not clear to me what should I do here.
