### ISSUE TITLE
No basic usage documentation in TeXLive (2019)

### ISSUE THREAD

**Issue by jfbu** [alif-type/xits#71]
Trying

```
$ texdoc -l xits
 1 /usr/local/texlive/2019/texmf-dist/doc/fonts/xits/README.txt
   = Readme
 2 /usr/local/texlive/2019/texmf-dist/doc/fonts/xits/FONTLOG.txt
 3 /usr/local/texlive/2019/texmf-dist/doc/fonts/xits/OFL-FAQ.txt
 4 /usr/local/texlive/2019/texmf-dist/doc/fonts/xits/OFL.txt
Enter number of file to view, RET to view 1, anything else to skip: 
```

I do not get any immediately copyable information "for LaTeX dummies" such as ``\setmathfont{XITS Math}``. I think there was in the past. This can be a difficulty when a LaTeX user hears about XITS. It is indeed often a big problem to know the names to use with fontspec/unicode-math, and documentation by font authors is useful. I found it here on the repo.

**Comment by khaledhosny** [comment]
There is https://github.com/alif-type/xits/blob/master/documentation/user-guide.pdf

**Comment by khaledhosny** [comment]
I know longer include it in the tarball though as it was written in ConTeXt and I’m no longer able to get it to compile. It didn’t seem to be very useful either.

**Comment by jfbu** [comment]
> There is https://github.com/alif-type/xits/blob/master/documentation/user-guide.pdf

Indeed, this is how I found out (again) about `\setmathfont{XITS Math}`. I lack imagination :) and persitent memory :).

The github interface rendered the PDF strangely though. The README does include a link to this github repo, perhaps including the full link to the user-guide.pdf would help even more.

IMHO some kind of gentle help to normal LaTeX users is needed even if it is only to say `\setmathfont{XITS Math}`. Or, perhaps unicode-math contains examples of usage of XITS? then perhaps tell users to open up unicode-math documentation (and potentially read it).

**Comment by jfbu** [comment]
> The github interface rendered the PDF strangely though.

Sorry, my Firefox was configured to not authorize fonts specified by the web page. After authorizing it the PDF renders fine on the github interface.

**Comment by khaledhosny** [comment]
I don’t think I’m going to write such documentation nor that I’m convinced that every font should provide documentation, but contributions are welcomed.
