### ISSUE TITLE
Unite Adam Twardoch's Schticks Text (link below) and this XITS project

### ISSUE THREAD

**Issue by cssobral2013** [alif-type/xits#72]
The problem would be, how to implement Schitcks Text's 162 weights into XITS?

Link to Twardoch's Schticks Text:
https://github.com/twardoch/schticks-fonts-ofl

**Comment by khaledhosny** [comment]
This is based on [STIX Two](https://github.com/stipub/stixfonts/) fonts, while XITS is based on the older version of STIX fonts. These basically are completely different fonts and there is nothing to merge.

**Comment by cssobral2013** [comment]
Sorry for that. I didn't realize that XITS is based on 1st version of STIX.

Em sáb, 4 de mai de 2019 16:28, Khaled Hosny <notifications@github.com>
escreveu:
