### ISSUE TITLE
Old-style figures?

### ISSUE THREAD

**Issue by dbenjaminmiller** [alif-type/xits#75]
XITS does have support for old-style figures (taken from STIX), but if you try to use them I think you'd have to agree that they are incredibly ugly, to the point of uselessness, essentially. They have very strange design and metrics. Really, I don't know how they were accepted for STIX in the first place. I am up to design OSF to match Linotype Times, but before doing so I'd like to ask if they'd possibly be accepted in XITS — I know that you usually are against replacing STIX characters but I think these are so bad that there would be no loss. They could be kept around as a cv if _really_ desired.

**Comment by khaledhosny** [comment]
The only concern I have (since this project is in maintenance mode) is changing glyph metrics and potentially causing line breaking changes to existing documents using the font. So the new glyphs should either have the exact metrics (glyph advances, and kerning if any) or be made into a stylistic set.

**Comment by dbenjaminmiller** [comment]
![Screenshot_2019-08-07_16-44-18](https://user-images.githubusercontent.com/43855846/62656811-07645f80-b933-11e9-84ec-1372470eaabb.png)

The spacing and design are so horrendous I can't imagine they are being used…

**Comment by dbenjaminmiller** [comment]
I now have OSF and smallcaps, donated by URW just today under the OFL. The smallcaps (compatible with Adobe's) I am adding to XITS straight up; since there are no SC, there is no issue. The OSF I suppose I will add as a stylistic set, as zero.onum.ss10, etc., unless you would like me to make them the default and the others the stylistic set. There are only 9 stylistic sets currently, yes, so ss10 is good?

**Comment by khaledhosny** [comment]
As a general rule, for this particular project, I want to maintains table metrics (glyph and line) indefinitely, so a new glyph with different metrics will be an optional alternate. Completely new additions are OK of course.

**Comment by dbenjaminmiller** [comment]
Great. I will add them as ss10. I believe they will only show when both osf
and ss10 are enabled (I consider this correct --- since it will be easier
when using it, so they show only in contexts in which osf would normally be
used). The small caps and the new OSF will only be in the regular font, in
accordance with the Adobe and URW sources having them only for regular. I
don't think I will add them to the math font, unless you think that is
useful.

**Comment by khaledhosny** [comment]
Smallcaps in the math font are not required. What about bold and italic styles, do they get them as well?

**Comment by dbenjaminmiller** [comment]
Unfortunately not. They were not in the Adobe Times font in the first
place, so they were not drawn by URW. I might eventually draw them myself
but only after I do my Palatino smallcaps clone project, Domitian, and
maybe finish my original font too. Unless you know of a particular
professional font to try to clone. But keep in mind that these are true
small caps, not petite caps like Termes has. See notes in newtx
documentation iirc.

**Comment by khaledhosny** [comment]
Sounds good. Regular is better than nothing.

**Comment by dbenjaminmiller** [comment]
Yes. And with this, XITS is now a complete replacement for Adobe Times, and
can be used in a drop-in fashion (though 100% compatibility is only with
ss10 in osf). This will make it very useful as this is often what is found
in journals of course. Do you think these additions mean I should bump the
version to 1.300 as well? And then I figure we can push it out to CTAN
after, as they haven't gotten the updates for a while.

**Comment by khaledhosny** [comment]
Sure, once you are done I’ll cut a new release.

**Comment by dbenjaminmiller** [comment]
Yeah, I will just need some time because there were some differences from Adobe which I am just rectifying here (the design of one.onum, specifically — but I have changed that) — and I just need to make sure the metrics are compatible with Adobe's, and then I will push.

**Comment by dbenjaminmiller** [comment]
Also, it appears that Adobe later added them in current releases of the font. I can try to draw based on images from there but I won't be doing that for a while.

**Comment by dbenjaminmiller** [comment]
It will be ss11 (since I realize now there is a ss10 not mentioned in the docs)… and ss12 will be all lining osf (ss11 will have a proportional one.onum.ss11). I still need to write the feature file for the small capitals and c2sc and then I'll send a pr

**Comment by dbenjaminmiller** [comment]
I'm taking a while to design the SC based on URW source, since URW does not match Adobe and STIX I am fixing it so it does … once I'm done I'll send.

**Comment by dbenjaminmiller** [comment]
Realizing that the small caps didn't match up (as they were Monotype-matching rather than Linotype-matching), I redid every single character individually to make it fit the design… it took me all yesterday and today… and AS I was importing the feature file for the kerning into fontforge, it crashed, deleted all the glyphs and left no trace in autosave… I am quite disheartened to say the least. I may do it again but it will be a while until I have the time.

**Comment by khaledhosny** [comment]
Sorry about that. I feel your pain, my laptop was stolen last month and I lost lots of unfinished work like this.

**Comment by dbenjaminmiller** [comment]
Sorry to hear, it's always frustrating when you've done what you want and
you have to begin from scratch again.

FF has crashed for me a lot. I have some consideration for writing a new
font editor from scratch (as I am not impressed with Trufont). I know that
realistically I don't have the time to write something like this but maybe
I will try to write a toy editor which can do a single-glyph view from FF
single-glyph files.

I know you've also mentioned the need for a new FOSS font editor before
(besides your attempt at fixing up FF). I'm thinking beginning by making a
single-glyph editor maybe to make the apparently Sisyphean task a little
more surmountable. Maybe this is not a good viewpoint, let me know what you
think. I mean, I know that most of us FOSS folk are using FF but I don't
know of anybody who actually thinks it's any good…

**Comment by khaledhosny** [comment]
I don’t know really, but the glyph editor in FontForge is one of its main strengthens and I have no idea how hard is it to replicate a good subset of its functionality, but I’m not good at these kinds of tasks either so it is mostly my own incompetence.

**Comment by dbenjaminmiller** [comment]
It's probably really difficult in some ways. The easiest implementation I
can think of involves making first off a reader for fontforge individual
glyph files… but I don't think I have the time for this kind of thing. Now
now, anyway.
