### ISSUE TITLE
Issue with line spacing in some programs

### ISSUE THREAD

**Issue by dbenjaminmiller** [alif-type/xits#77]
I do not have this problem in LuaLaTeX, but when typing using XITS in LibreOffice, it seems that the line spacing is quite wonky. I have attached a PDF including four different faces: Nimbus Roman, Times New Roman, XITS and ztm (from Michael Sharpe's nimbus15 package). For some reason, XITS and ztm are spaced differently (much more line spacing) from the former two fonts, even though in all instances the setting has been put on the same single spacing setting. (STIX exhibits the same behavior as XITS here, so it is not a new issue.) This same spacing issue occurs when using XITS as the text font in Firefox as well (ztm too).

Considering that this does not occur with LuaTeX, I think this is a bug (although it may simply be something wonky with this rending engine, these applications are very popular and it's clearly possible to avoid this in some way.)

I'm using LibreOffice and Firefox on Linux; I don't have Windows or MacOS at hand so I can't tell if these issues are present on the versions on those platforms. I also don't know if, e.g., Word is affected. Testing with Chromium shows the same issue.

[weird spacing.pdf](https://github.com/alif-type/xits/files/3511937/weird.spacing.pdf)

**Comment by khaledhosny** [comment]
*TeX does not use line spacing settings from the fonts, LibreOffice does. STIX/XITS has larger line spacing by default, I don’t know why for sure since I just inherited it but it is too late to change it anyway.

**Comment by dbenjaminmiller** [comment]
Fair enough. Weird design choice but we can't change that, I guess. *TeX's results are much more palatable to me but that's the way it is.

**Comment by khaledhosny** [comment]
In LibreOffice/Firefox/Chrome, you can set line spacing explicitly and override what the font provides. Personally I prefer looser than tighter line spacing.

**Comment by dbenjaminmiller** [comment]
Sure, but I'd prefer not having to set these things on an application level (I'm also not 100% sure on how to set the line-height in FF for all pages using the default serif font only using user stylesheets … not that it's too important). I suppose it is a quick mod which I'll do for myself.
