### ISSUE TITLE
Circumflex and diaresis misplaced on lowercase i

### ISSUE THREAD

**Issue by dbenjaminmiller** [alif-type/xits#78]
not on other vowels, nor on capital I, it seems, nor with other accents: but see this:

Inherited from STIX but this is an obvious bug (these accents are placed too far right.) Affects regular, italic, italic and bold italic.

![Screenshot_2019-08-17_11-51-26](https://user-images.githubusercontent.com/43855846/63214392-a92f3d80-c0e5-11e9-998e-22401c1e0990.png)

sample lines in XITS and Nimbus Roman for comparison; the vowels below are all XITS

**Comment by dbenjaminmiller** [comment]
Actually, it seems that it's more that the i itself is too far left:

![Screenshot_2019-08-17_11-57-04](https://user-images.githubusercontent.com/43855846/63214440-25298580-c0e6-11e9-836b-c80703a54b45.png)

**Comment by khaledhosny** [comment]
Can you provide the actual string, what application is this?

**Comment by dbenjaminmiller** [comment]
Not application-specific. This is an issue with the design of î and ï. Open up the font in FontForge and you will see the defect in these two characters.

**Comment by khaledhosny** [comment]
I see, I thought it is an issue with mark positioning (which we don’t handle), but I now see that the i part is displaced in these glyphs.

**Comment by dbenjaminmiller** [comment]
Yep. I would say it is a pretty big QC issue in French, and should probably be fixed in the release version quickly and not just the master … I'm just surprised it wasn't caught earlier.

**Comment by dbenjaminmiller** [comment]
I just checked, and Type1 STIX is affected as well. So the issue is ancient.

**Comment by khaledhosny** [comment]
I’m fixing them. Though I don’t see the urgency given how long they have been broken.

**Comment by dbenjaminmiller** [comment]
Fair if you don't, I suppose. I am a bit surprised that STI didn't catch them though

**Comment by dbenjaminmiller** [comment]
Issue still present in the italic and bold italic. Slightly more subtle but same problem.

**Comment by khaledhosny** [comment]
I did check these fonts and the accented i glyphs had the i at the same place as the dotless i (unless the dotless i is misplaced as well).

**Comment by dbenjaminmiller** [comment]
Just took a look. you're right that the base glyph is not misplaced. In these fonts, it seems that it is the accent, rather, which is off.

**Comment by khaledhosny** [comment]
That is probably subjects. I checked Times (that ships with macOS) and it is very close to XITS. Times New Roman is lightly different, but its accents are smaller too.

**Comment by dbenjaminmiller** [comment]
![image](https://user-images.githubusercontent.com/43855846/63218503-3d22f880-c12a-11e9-9d8a-0076d77e8ab6.png)
Background is Mac Times.

**Comment by khaledhosny** [comment]
Which why I said very close, not identical. I don’t think it has to be identically placed and it does not look misplaced to me, but feel free to change if you strongly feel so.

**Comment by dbenjaminmiller** [comment]
Upon further inspection, the italic fonts seem fine in print.
