### ISSUE TITLE
Arrays and systems of equations

### ISSUE THREAD

**Issue by Aldo-aldo** [alif-type/xits#79]
In systems of equation and in arrays the lines are too attached
![Annotazione 2019-08-23 184116](https://user-images.githubusercontent.com/54449266/63608633-c4161c00-c5d5-11e9-93f9-2084036a8da9.png)
The figure displays the arrays in Xits Math (first) and in Cambria Math (second one) in Word of Microsoft Office 2019
![Annotazione 2019-08-23 184144](https://user-images.githubusercontent.com/54449266/63608647-ca0bfd00-c5d5-11e9-96ea-e01ba8905c1e.png)

**Comment by khaledhosny** [comment]
Not sure what I should be looking at in the second image.

**Comment by Aldo-aldo** [comment]
Dear Khaled,
the image

[image: image.png]
compare as an array appers in MS Word with Xits Math and Cambria Math. I
use this program to write a math book for my student and I prefer Xits font
because the text is more homogeneous, but the math editor of word does not
allow you to adjust the vertical line spacing between the equations which
is predefined for the mathematical font you use. So the equations in a
system are too cloose, especially if there are fractions within them.
Thanks for the reply,
Aldo

Il giorno dom 25 ago 2019 alle ore 01:59 Khaled Hosny <
notifications@github.com> ha scritto:

**Comment by khaledhosny** [comment]
Sorry, but GitHub will not show images when you reply with email. I have no idea how the space between the lines is determined either in these situations, so I don’t know what should I change in the font.

**Comment by dbenjaminmiller** [comment]
I'm not sure that there is an actual issue. It doesn't have the same metrics as Cambria Math, sure. But if you feel it's too tight I assume there is some way to adjust spacing (though I do not have Word).

**Comment by Aldo-aldo** [comment]
I attach the image that wasn't visible in the previous email

Il
26.08.2019 05:07 Khaled Hosny ha scritto: 

> Sorry, but GitHub will not
show images when you reply with email. I have no idea how the space
between the lines is determined either in these situations, so I don't
know what should I change in the font. 
> 
> --
> You are receiving this
because you authored the thread.
> Reply to this email directly, view it
on GitHub [1], or mute the thread [2].

An array with Cambria Math  


The same array with Xits Math    
  


Con OpenStar hai Giga, SMS e i minuti che vuoi da 4,99€ al mese, per sempre. Cambi gratis quando e come vuoi e in più hai 6 mesi di INFINTY! http://tisca.li/myopen

**Comment by Aldo-aldo** [comment]
unfortunately it is not possible to vary the vertical space between
the equations from the editor math of MS word, as shown in the attached
figure. There is no option to do this, nor a unicode math command like
...

Il 26.08.2019 05:17 D. Benjamin Miller ha scritto: 

> I'm not sure
that there is an actual issue. It doesn't have the same metrics as
Cambria Math, sure. But if you feel it's too tight I assume there is
some way to adjust spacing (though I do not have Word). 
> 
> --
> You
are receiving this because you authored the thread.
> Reply to this
email directly, view it on GitHub [1], or mute the thread [2].
 



Con OpenStar hai Giga, SMS e i minuti che vuoi da 4,99€ al mese, per sempre. Cambi gratis quando e come vuoi e in più hai 6 mesi di INFINTY! http://tisca.li/myopen

**Comment by Aldo-aldo** [comment]
![Annotazione 2019-08-26 115548](https://user-images.githubusercontent.com/54449266/63683549-ff456480-c7fa-11e9-9b00-059ef3e9127c.png)

**Comment by khaledhosny** [comment]
I still don’t know how Word calculates this, and even if I did it is unlikely to change since it would cause reflow of existing documents.

**Comment by Aldo-aldo** [comment]
If the reflow of existing documents is for the better, why not try it? I don't want to insist yet, having this font is a big step forward

**Comment by Aldo-aldo** [comment]
I have attached an extract both as a word document and a pdf file
[Un estratto.docx](https://github.com/alif-type/xits/files/3544625/Un.estratto.docx)
[Un estratto.pdf](https://github.com/alif-type/xits/files/3544633/Un.estratto.pdf)
