### ISSUE TITLE
backport?

### ISSUE THREAD

**Issue by dbenjaminmiller** [alif-type/xits#80]
Considering the new features being added to XITS (the small caps and osf which I'll commit soon) and the bug fixes (e.g., accents on i), the STIX package on CTAN is out of date. While STI probably wants that package frozen, there are still some uses which require Type 1 fonts (e.g., most notably, arXiv). So I am thinking of backporting the changes from XITS into a classic TeX Type 1-based package. I can do this myself (unless you'd particularly like to do it for whatever reason), but I ask whether you're OK with me calling this xits-type1 or if I should come up with a new name.

**Comment by khaledhosny** [comment]
Sure, you can use the name if its is based on XITS.

It was me who did the Type 1 version of STIX for STIPub, but I’d never volunteer to do it, it feels so backwards.

**Comment by dbenjaminmiller** [comment]
It is, and looking at the implementation of math support it might not be
worth my time. I don't understand why arXiv doesn't just support the use of
LuaTeX or XeTeX yet. If I do it I might just take the current STIX package
as you've set it up and replace the changed characters, etc.
