### ISSUE TITLE
Some accented glyphs missing kerning

### ISSUE THREAD

**Issue by dbenjaminmiller** [alif-type/xits#81]
I'm not fixing it in my forthcoming PR (although I may do it further down the line if I have time): the accented glyphs after Ÿ/ÿ don't have kerning. They should be kerned in accordance with the kerning of their base character (except in obvious cases like the N with initial apostrophe).

**Comment by khaledhosny** [comment]
If the kerning is seriously broken, then that counts like a bug that I’m willing to compromise the stability promise for fixing it.

**Comment by dbenjaminmiller** [comment]
Yeah, it is a simple problem; many of the Latin extended characters are
just absent from the kerning tables even though the base characters are
there. I would advise holding off on fixing until after I commit my small
caps etc. later tonight as they have kerning as well (once I finish
adjusting that). We'll have to check to make sure that the accent placement
doesn't interfere. Then we can do that + my new characters as 1.300, I'd
say.

**Comment by khaledhosny** [comment]
OK.

**Comment by dbenjaminmiller** [comment]
This applies even to basic accented characters such as Ã, it seems. In any case, I checked, and more uppercase characters should be kerned the exact same way as the base character (some are of different width, such as Î, and require slightly different kerning, with the principle that the difference between the base character and the other character kerned remain the same). I don't know if there is a way to do this automatically, perhaps? Or will we have to do it manually (and tediously)? I'm not referring to autokerning — that's not what we want — but simply copying, day, the kerning for G to Ĝ, etc.

**Comment by dbenjaminmiller** [comment]
Fixing this may be a lot of work. Perhaps let's cut the current version as 1.300 and tackle the kerning in 1.301?

**Comment by khaledhosny** [comment]
I just cut 1.300 release.

**Comment by dbenjaminmiller** [comment]
Great. I had sent a PR adding four more SC characters — hopefully this can be merged before everything is sent everywhere.

**Comment by dbenjaminmiller** [comment]
Since this change is obviously breaking (since documents will compile with very slightly different results), should the guiding principle be to kern as consistently as possible or to break as little as possible? I am switching the font to a class-based system instead of a pair-based one. (This in itself does not necessarily change output, and results in a smaller font file.)

(To consider:) Q, when the right character in the pair, always kerns as O does in the existing kerning. But it's not kerned for 100% of the pairs O is present in (i.e., it is omitted in less common combinations). Especially being that it will take no more space, should it be classed O in the second character category? I would say yes.

**Comment by dbenjaminmiller** [comment]
Further, some accented characters kern differently from their base characters, e.g., ã kerns differently from a. I assume we wish to retain this where it exists.

**Comment by khaledhosny** [comment]
I know this will upset you, but I’m starting to feel uneasy about this. I never officially promised metrics stability, but it was my intention when I put the fonts in maintenance mode two releases ago.

**Comment by dbenjaminmiller** [comment]
It makes sense to convert to class-based kerning over pair-based kerning in any case. This can be done without changing the actual results and is more efficient in terms of file size. It also makes it easier to manipulate the kerning table if one wishes to add more characters in the future. So I will send that in my next PR. Also, having the small caps kerning in a separate subtable from the other kerning cause the SC kerning not to load on some engines/platforms. So I will merge them into one table as well.

I think this is perhaps the best solution for maintaining maximum compatibility: for any character that is present at all in the kerning table, the current kerning will be preserved (as it exists in STIX/XITS 1.300). So Q will be kerned with the characters it is kerned with, and O with the characters it is kerned with, and no changes will be made to the kerning of these characters.

For the Latin-Extended characters which lack kerning _entirely_, kerning would be added as appropriate, in line with the behavior of the base characters and the kerned accented characters. This would only be done if the character is not kerned at all in the present version. That I feel is a fairly conservative solution.

Myself, I don't see why CO should kern differently from ÇO. I think the only reason this pair was not included was because it was not though to be common (for the same reason ck kerns, but çk doesn't). Of course, this saves space in a pair-based system, especially considering that many of these pairings are extremely rare, if even attested. In a class kerning it costs almost nothing to include this vastly expanded kerning support.

But here is what I figure I will do: I will send a PR which switches the current font to class-based kerning and which does not introduce or modify any kern pairs (i.e., a PR which preserves the metrics stability entirely).

This PR will have the following changes:
* Add 4 more accented characters for which small caps were accidentally omitted
* Correct positioning of new superscript and subscript characters
* Convert kerning to a class-based subtable
* Fix error on some platforms due to small caps kerning being in a separate subtable

This, I think, you will find appropriate. Then in the future we might or might not choose to add the kerning for Latin-Extended characters; in any case, that would be very easy to do.

**Comment by dbenjaminmiller** [comment]
I've decided that I will address this my own way in my own fork of the fonts. I have some other changes I'd like to make anyway, which are outside of XITS' scope. I will still contribute to XITS though.
