### ISSUE TITLE
Add more mark attachments

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [alif-type/xits#86]
Althrough XITS lakes some letters while comparing to STIX Two, it’s possible to implement them by adding more mark attachments.

Here is an Unicode charts for STIX Two Regular font, red letters are produced with combining diacritics, althrough they’re buggy. 
https://github.com/stipub/stixfonts/blob/master/docs/charts/StixTwoRegular.pdf

**Comment by khaledhosny** [comment]
Patches/pull requests are welcome.
