### ISSUE TITLE
Horizontal bar is exteremely wide

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [alif-type/xits#87]
The horizontal bar in XITS is sightly wider than many other fonts, to my suggestion, the glyph should be replaced by a new glyph based on em dash, and the previous glyph should be reencoded in U+2E3A.

**Comment by dbenjaminmiller** [comment]
This is an aspect of the STIX design, so, in line with the principle of backwards compatibility, shouldn't be changed in XITS unless it were found to be a true misencoding.

**Comment by khaledhosny** [comment]
What is horizontal bar and why it matters if it is wider than other fonts. As @dbenjaminmiller already mentioned, we no longer do any changes that would cause text reflow unless it is a clear bug.

**Comment by KrasnayaPloshchad** [comment]
Horizontal bar (aka quotation dash) is used to introduce quoted text, it’s non breakable in some software environments. 
See: https://en.wikipedia.org/wiki/Quotation_mark
What makes me weird is the horizontal bar looks 2x wider than em dash, which I have never seen before I used XITS, and STIX Two seems fixed that, so I thought it’s a wrong design and it should be fix.

**Comment by khaledhosny** [comment]
You still didn’t tell me which character (Unicode code point) you are talking about. Anyway, metrics are not going to change any more.
