### ISSUE TITLE
Math italic i/j spacing

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [alif-type/xits#89]
This is similar to another user reported to the Libertinus font. The bug is fixed in Libertinus Math, but still present in XITS Math.

[Test ij.zip](https://github.com/alif-type/xits/files/3591916/Test.ij.zip)
(This is produced with LibreOffice, TexMaths and TeX Live)

**Comment by khaledhosny** [comment]
Too late. People had 10 years to complain about this.
