### ISSUE TITLE
Display variants of big operators have wrong “depth”

### ISSUE THREAD

**Issue by OlivierNicole** [alif-type/xits#90]
While implementing a math layout algorithm, I noticed some strange disparities between my output (top) and LuaLaTeX's (bottom) with big operators in display style:

![Capture d’écran_2019-10-06_00-18-18](https://user-images.githubusercontent.com/14031333/66261509-fc149f80-e7ce-11e9-9a61-557dc185ba3d.png)

In the first equation, the product operator has no “depth”, i.e. is entirely above the baseline, which is strange. The depth of the display integral sign is too small, too.

According to what I can see in Fontforge, the display-style product (glyph `uni220F.display`) indeed has no depth. Is this a problem in the font design, or am I missing something?

(Edit.: use better screenshot)

**Comment by OlivierNicole** [comment]
Here is a screenshot with debug boxes on, which make the problem more visible:

![Capture d’écran_2019-10-06_00-02-24](https://user-images.githubusercontent.com/14031333/66261533-6c232580-e7cf-11e9-9c03-825a4c18e28b.png)

**Comment by khaledhosny** [comment]
I don’t remember the exact details, but some glyphs are centered around the math base line (using the glyph height from its bounding box). I think big operators belong to this group.

**Comment by OlivierNicole** [comment]
Is there a marker in the font that indicates this fact, or is it an external convention?

**Comment by khaledhosny** [comment]
External logic.

**Comment by OlivierNicole** [comment]
It is a bit unfortunate because it requires specific code for things that could be handled entirely by the generic glyph drawing functions. Is there a particular reason for this state of things?

**Comment by khaledhosny** [comment]
No idea, but I think it is because these rules are not fixed, the same glyph can be used as operator and as something else and it is up to the layout engine to detect and handle that. For the exact rules, you probably need to check The TeX Book (Appendix G), [Appendix G illuminated](https://www.tug.org/TUGboat/tb27-1/tb86jackowski.pdf), and [OpenType Math Illuminated](https://www.tug.org/~vieth/papers/bachotex2009/ot-math-paper.pdf).

**Comment by OlivierNicole** [comment]
I will look it up. Thank you for your help!
